version: 0.2

phases:
  build:
    commands:
      - echo Entered the install phase...
      - cd repository/portfolio && npm install --production
      - cd $CODEBUILD_SRC_DIR/../repository/portfolio && npm install --production
      - npm install --production
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - '*.html'
    - favicon.icon
    - styles/main.css
    - images/*
    - dist/bundle.js
    - '*.json'
    - '*.js'
  base-directory: 'repository/portfolio'
