version: 0.2

phases:
  build:
    commands:
      - echo Entered the install phase... v2
      - cd repository/portfolio && npm install
      - npm run webpack
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - '*.html'
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
    - '*.json'
    - '*.js'
  base-directory: 'repository/portfolio'
