version: 0.1

phases:
  build:
    commands:
      - echo start
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - *.html
    - favicon.icon
    - styles/main.css
    - images/*
  base-directory: 'repository/portfolio'
