version: 0.1

phases:
  build:
    commands:
      - mv repository/portfolio/**/* ./
      - rm -R repository/portfolio
  post_build:
    commands:
      - echo hola
artifacts:
  files:
    - index.html
    - favicon.icon
    - styles/main.css
    - images/*
