version: 0.1

phases:
  build:
    commands:
      - mv repository/portfolio/**/* ./
      - rm -R repository/portfolio
  post_build:
    commands:
      - echo hola
artifacts:
  files:
    - repository/portfolio/index.html
    - repository/portfolio/favicon.icon
    - repository/portfolio/styles/main.css
    - repository/portfolio/images/*
