version: 0.2

phases:
  build:
    commands:
      - cd repository/portfolio && npm install
      - cd repository/portfolio && npm run webpack
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - '*.html'
    - favicon.icon
    - styles/main.css
    - images/*
    - dist/bundle.js
  base-directory: 'repository/portfolio'
