service: koitoersite

frameworkVersion: ">=1.9.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  rootDomain: koitoer.com
  devDomains:
    - test.koitoer.com
  prodDomains:
    - www.koitoer.com
    - koitoer.com
  devCognitoPool: 'arn:aws:cognito-idp:us-east-1:757639574144:userpool/us-east-1_qLwRiooaV'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x

functions:
  presign:
    handler: backend/pre_signup.handler
  test:
    handler: backend/test_auth.handler
    events:
    - http:
        cors: true
        authorizer:
          name: pool_auth
          arn: '${self:custom.${self:custom.stage}CognitoPool}'
        path: /test
        method: get
  gql:
    handler: backend/gql_endpoint.handler
    events:
    - http:
        authorizer:
          name: pool_auth
          arn: '${self:custom.${self:custom.stage}CognitoPool}'
        cors: true
        path: /gql
        method: post

resources:
  Mappings: ${file(resources/mappings.yml)}
  Outputs: ${file(resources/outputs.yml)}
  Resources:
    WebSite:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
    ##DnsRecords: ${file(resources/${self:custom.stage}-dns.yml)} -- Route53 already exists
    ##SSLCert: ${file(resources/${self:custom.stage}-ssl.yml)} -- Don't need to be created as it already exists.
    CDN:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          ViewerCertificate:
            AcmCertificateArn: "arn:aws:acm:us-east-1:757639574144:certificate/ccf0799d-2569-4f99-85e6-f5ad31cd37c0"
            SslSupportMethod: sni-only
          Enabled: true
          HttpVersion: http2
          Aliases: ${self:custom.${self:custom.stage}Domains}
          DefaultRootObject: index.html
          Origins:
            - DomainName: {"Fn::Join": ["", [{Ref: WebSite}, ".", {"Fn::FindInMap": [RegionMap, {Ref: "AWS::Region"}, websiteendpoint]}]]}
              Id: S3Origin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            ViewerProtocolPolicy: allow-all
            TargetOriginId: S3Origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            DefaultTTL: 30
            MinTTL: 10
            ForwardedValues:
              QueryString: true

package:
  exclude:
    - bin/**
    - static/**
    - resources/**
    - package.json
    - node_modules/**
  include:
    - node_modules/uuid/**
    - node_modules/lodash/**
    - node_modules/graphql/**
    - node_modules/iterall/**
